DASH_APP:
  APP_TITLE: Cosmic Ray Flux Measurement At GSU
  UPDATE_TITLE: Updating...
  DEBUG: TRUE

DASH_THEME:
  THEME: LITERA

TEMPLATE:
  LOGO_SOURCE: 
  WATERMARK_SOURCE: 
  SHOW_LEGEND_INSIDE: False
  SHOW_RANGESELECTOR: False